#!/usr/bin/env python3
"""
Pre-push cleanup and optimization script.
1. Cleans scratch files, test outputs, and caches.
2. Formats and lints Python code using Ruff (auto-installs if missing).
3. Lints and builds the Next.js frontend to minify and optimize assets.
4. Installs itself as a Git pre-push hook when run with --install.
"""

import os
import sys
import shutil
import subprocess
import argparse
from pathlib import Path

# Color helpers
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
BLUE = "\033[94m"
RESET = "\033[0m"


def log(msg, color=RESET):
    print(f"{color}{msg}{RESET}")


def get_workspace_root():
    # The workspace root is the parent of the scripts directory
    return Path(__file__).resolve().parent.parent


def get_venv_python(root):
    # Detect virtual environments
    venv_paths = [
        root / ".venv" / "Scripts" / "python.exe",  # Windows
        root / ".venv" / "bin" / "python",  # Unix
        root / "venv" / "Scripts" / "python.exe",
        root / "venv" / "bin" / "python",
    ]
    for p in venv_paths:
        if p.exists():
            return str(p)
    return sys.executable


def install_hook(root):
    git_dir = root / ".git"
    if not git_dir.exists():
        log("Error: .git directory not found. Are you in a Git repository?", RED)
        sys.exit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    hook_path = hooks_dir / "pre-push"

    hook_content = """#!/bin/sh
# Pre-push hook generated by scripts/pre_push_clean_opt.py

# Redirect output to stderr.
exec 1>&2

echo "=================================================="
echo "Running Pre-Push Cleanup & Optimization..."
echo "=================================================="

# Detect Python interpreter from virtual environment or path
if [ -f "./.venv/Scripts/python" ]; then
    PYTHON_BIN="./.venv/Scripts/python"
elif [ -f "./.venv/bin/python" ]; then
    PYTHON_BIN="./.venv/bin/python"
elif [ -f "./venv/Scripts/python" ]; then
    PYTHON_BIN="./venv/Scripts/python"
elif [ -f "./venv/bin/python" ]; then
    PYTHON_BIN="./venv/bin/python"
else
    PYTHON_BIN="python"
fi

$PYTHON_BIN scripts/pre_push_clean_opt.py
STATUS=$?

if [ $STATUS -ne 0 ]; then
    echo "[ERROR] Pre-push check FAILED. Git push aborted."
    exit 1
else
    echo "[SUCCESS] Pre-push check PASSED. Proceeding to push..."
    exit 0
fi
"""

    # Write the hook
    with open(hook_path, "w", newline="\n") as f:
        f.write(hook_content)

    # Make executable (chmod +x)
    try:
        os.chmod(hook_path, 0o755)
        log(f"Successfully installed Git pre-push hook at {hook_path}", GREEN)
    except Exception as e:
        log(f"Hook written, but failed to set executable permissions: {e}", YELLOW)
        log(f"Please run: chmod +x {hook_path}", YELLOW)


def run_cleanup(root):
    log("\n=== Phase 1: Cleaning scratch files and caches ===", BLUE)

    ignored_dirs = {".git", ".venv", "venv", "node_modules", ".next"}
    deleted_files_count = 0
    deleted_dirs_count = 0

    # Files to delete at root level
    root_files_to_delete = ["test_out.txt"]
    for f_name in root_files_to_delete:
        f_path = root / f_name
        if f_path.exists():
            try:
                os.remove(f_path)
                log(f"  Deleted root file: {f_path.relative_to(root)}")
                deleted_files_count += 1
            except Exception as e:
                log(f"  Error deleting {f_name}: {e}", RED)

    # Root level scratch directory
    scratch_dir = root / "scratch"
    if scratch_dir.exists() and scratch_dir.is_dir():
        try:
            shutil.rmtree(scratch_dir)
            log("  Deleted root scratch directory: scratch/")
            deleted_dirs_count += 1
        except Exception as e:
            log(f"  Error deleting scratch directory: {e}", RED)

    # Walk the project directory
    for dirpath, dirnames, filenames in os.walk(root):
        # Exclude ignored directories in-place to prevent os.walk from entering them
        dirnames[:] = [d for d in dirnames if d not in ignored_dirs]

        path_obj = Path(dirpath)

        # Check for directory deletion (e.g. __pycache__, .pytest_cache, .eslintcache, .ruff_cache)
        for d in list(dirnames):
            if d in ("__pycache__", ".pytest_cache", ".eslintcache", ".ruff_cache"):
                d_path = path_obj / d
                try:
                    shutil.rmtree(d_path)
                    log(f"  Deleted cache directory: {d_path.relative_to(root)}")
                    dirnames.remove(d)  # Don't recurse into deleted directory
                    deleted_dirs_count += 1
                except Exception as e:
                    log(f"  Error deleting directory {d_path}: {e}", RED)

        # Check for scratch files or test outputs
        for f in filenames:
            f_path = path_obj / f
            # Match rules:
            # 1. Python compiled files (*.pyc, *.pyo, *.pyd)
            # 2. Temporary/scratch files matching "scratch_*" or "*_scratch.py" or "temp_*" or "test_temp_*"
            should_delete = False
            if f.endswith((".pyc", ".pyo", ".pyd")):
                should_delete = True
            elif (
                f.startswith("scratch_")
                or f.startswith("temp_")
                or f.startswith("test_temp_")
                or f.endswith("_scratch.py")
            ):
                should_delete = True

            if should_delete:
                try:
                    os.remove(f_path)
                    log(f"  Deleted scratch/cache file: {f_path.relative_to(root)}")
                    deleted_files_count += 1
                except Exception as e:
                    log(f"  Error deleting file {f_path}: {e}", RED)

    log(
        f"Cleanup complete. Deleted {deleted_files_count} file(s) and {deleted_dirs_count} directory/directories.",
        GREEN,
    )


def run_python_optimization(root, python_bin):
    log("\n=== Phase 2: Optimizing Python codebase ===", BLUE)

    # 1. Check if ruff is installed
    log(f"Using Python: {python_bin}")
    try:
        subprocess.run(
            [python_bin, "-m", "ruff", "--version"], capture_output=True, check=True
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        log("Ruff not found. Installing Ruff inside virtual environment...", YELLOW)
        try:
            subprocess.run([python_bin, "-m", "pip", "install", "ruff"], check=True)
            log("Ruff installed successfully.", GREEN)
        except Exception as e:
            log(f"Failed to install Ruff: {e}", RED)
            sys.exit(1)

    # 2. Run Ruff Format
    log("Running ruff format...", YELLOW)
    try:
        subprocess.run([python_bin, "-m", "ruff", "format", "."], cwd=root, check=True)
        log("Python files formatted successfully.", GREEN)
    except subprocess.CalledProcessError as e:
        log(f"Ruff format failed: {e}", RED)
        sys.exit(1)

    # 3. Run Ruff Lint & Autofix
    log("Running ruff check with autofixes...", YELLOW)
    try:
        subprocess.run(
            [python_bin, "-m", "ruff", "check", "--fix", "."], cwd=root, check=True
        )
        log("Python linting checks and autofixes completed successfully.", GREEN)
    except subprocess.CalledProcessError as e:
        log(
            f"Ruff linting check failed: {e}. Please resolve linting errors before pushing.",
            RED,
        )
        sys.exit(1)


def run_frontend_optimization(root):
    frontend_dir = root / "frontend"
    if not frontend_dir.exists():
        log("\n[WARN] Phase 3 skipped: frontend/ folder not found.", YELLOW)
        return

    log("\n=== Phase 3: Optimizing & Minifying Next.js Frontend ===", BLUE)

    # Check if node_modules exists, run npm install if not
    node_modules_dir = frontend_dir / "node_modules"
    if not node_modules_dir.exists():
        log("node_modules folder not found. Running npm install...", YELLOW)
        try:
            subprocess.run("npm install", shell=True, cwd=frontend_dir, check=True)
            log("npm install completed.", GREEN)
        except subprocess.CalledProcessError as e:
            log(f"npm install failed: {e}", RED)
            sys.exit(1)

    # 1. Run Linting
    log("Running frontend linter (npm run lint)...", YELLOW)
    try:
        subprocess.run("npm run lint", shell=True, cwd=frontend_dir, check=True)
        log("Frontend linting passed.", GREEN)
    except subprocess.CalledProcessError as e:
        log(
            f"Frontend linting failed: {e}. Please fix lint errors before pushing.", RED
        )
        sys.exit(1)

    # 2. Run Production Build (compilation, tree-shaking, and minification)
    log(
        "Running frontend build (npm run build) to compile, optimize, and minify...",
        YELLOW,
    )
    try:
        subprocess.run("npm run build", shell=True, cwd=frontend_dir, check=True)
        log(
            "Frontend build succeeded. Assets compiled, optimized, and minified.", GREEN
        )
    except subprocess.CalledProcessError as e:
        log(
            f"Frontend build failed: {e}. Build must succeed before pushing to remote.",
            RED,
        )
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Pre-push cleanup, optimization, and minification script."
    )
    parser.add_argument(
        "--install",
        action="store_true",
        help="Install the script as a Git pre-push hook.",
    )
    args = parser.parse_args()

    root = get_workspace_root()

    if args.install:
        install_hook(root)
        return

    # Run core script operations
    python_bin = get_venv_python(root)

    run_cleanup(root)
    run_python_optimization(root, python_bin)
    run_frontend_optimization(root)

    log("\n[SUCCESS] All pre-push operations completed successfully!", GREEN)


if __name__ == "__main__":
    main()
